version: '2'

services:
  nginx:
    ports:
      - "${NGINX_FRONTEND_PORT}:80" # Хз, на винде почему-то
      - "${NGINX_BACKEND_PORT}:81"  # не работает build
      - "${NGINX_STORAGE_PORT}:82"  # если использовать переменные .env и запускать через баш-скрипт
    build:
      context: ./containers/nginx
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        PROJECT_PREFIX: ${PROJECT_PREFIX}
    container_name: "${PROJECT_PREFIX}_nginx" # снова траблы на винде, нужно жёстко указать префикс
    depends_on:
      - mysql
    volumes:
      - ./../:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    restart: unless-stopped
    environment:
      APP_ENV: ${YII_ENV}
      PROJECT_PREFIX: ${PROJECT_PREFIX}
    env_file:
      - .env

  php:
    build:
      context: ./containers/php
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        APP_ENV: "$YII_ENV"
    container_name: "${PROJECT_PREFIX}_php" # снова траблы на винде, нужно жёстко указать префикс
    volumes:
      - ./../:/var/www/html
      - ./logs/php:/var/log/php
      - ./data/sessions:/var/www/sessions
    links:
      - mysql
    restart: unless-stopped
    environment:
      APP_ENV: ${YII_ENV}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      PROJECT_PREFIX: ${PROJECT_PREFIX}
    env_file:
      - .env

  mysql:
    ports:
      - "3306:3306"
    build:
      context: ./containers/mysql
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: "${PROJECT_PREFIX}_mysql" # снова траблы на винде, нужно жёстко указать префикс
    environment:
      MYSQL_DATABASE: ${DB_USERNAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
